---
eu-med-as01:
  hostname: 10.1.10.102
  groups: ['uwaco_network']

pacific-as01:
  hostname: 10.1.10.28
  groups:
    - 'uwaco_network'
    - 'access'

ToR_esx01:
  hostname: 10.1.10.202
  groups: ['uwaco_datacenter']
  connection_options:
    netmiko:
       extras:
         device_type: 'cisco_ios_telnet'
    napalm:
      extras:
        optional_args:
          transport: 'telnet'
          secret: 'cisco'

arctic-as01:
  hostname: 10.1.10.100
  groups: ['uwaco_network']
  connection_options:
    netmiko:
       extras:
         device_type: 'cisco_ios_telnet'
    napalm:
      extras:
        optional_args:
          transport: 'telnet'
          secret: 'cisco'

# Dummy host to test failure
test-fail:
  hostname: 1.2.3.4
  groups: ['uwaco_network']

