---
eu-med-as01:
  hostname: 10.1.10.102
  groups: ['uwaco_network']


pacific-as01:
  hostname: 10.1.10.28
  groups:
    - 'uwaco_network'
    - 'access'


ToR_esx01:
  hostname: 10.1.10.202
  groups: ['uwaco_datacenter']
#  napalm_options: {'transport': 'telnet','secret': 'cisco'}


arctic-as01:
  hostname: 10.1.10.100
  groups: ['uwaco_network']
#  napalm_options: {'transport': 'telnet','secret': 'cisco'}

#
#test-fail:
#  hostname: 10.1.10.77
#  groups: ['uwaco_network']