---
eu-med-as01:
  nornir_host: 10.1.10.201
  groups: ['uwaco_network']


pacific-as01:
  nornir_host: 10.1.10.203
  groups:
    - 'uwaco_network'
    - 'access'


ToR_esx01:
  nornir_host: 10.1.10.202
  groups: ['uwaco_datacenter']
  napalm_options: {'transport': 'telnet','secret': 'cisco'}


arctic-as01:
  nornir_host: 10.1.10.100
  groups: ['uwaco_network']
  napalm_options: {'transport': 'telnet','secret': 'cisco'}

#
#test-fail:
#  nornir_host: 10.1.10.77
#  groups: ['uwaco_network']